name: planty_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  bloc: ^9.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_gen: ^5.12.0
  freezed_annotation: ^3.1.0
  go_router: ^17.0.1
  go_router_builder: ^4.1.3
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_lint: ^0.3.5
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  build_runner: ^2.10.4
  flutter_gen_runner: ^5.12.0

flutter:
  uses-material-design: true
