name: planty_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  bloc: ^9.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_gen: ^5.12.0
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  thing_toast: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  build_runner: ^2.10.4
  go_router_builder: ^4.1.3
  flutter_gen_runner: ^5.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/
